### ISSUE TITLE
help on this

### ISSUE THREAD

**Issue by Sharshofe** [PAXANDDOS/ForzaHorizon4Fix#8] opened 2023-10-01 00:04 UTC
this issue is happening in payday3 too and with golf with your friends and  a lot more 
i tried to edit the files so that it can work on payday 3 but it crashes after the 60 second counting finishes 
i tried two batch files for it 
![payday3pic](https://github.com/PAXANDDOS/ForzaHorizonFix/assets/78281327/552fe596-1e92-4364-bce4-2a60e734da60)
![payday3_2 0pic](https://github.com/PAXANDDOS/ForzaHorizonFix/assets/78281327/46647d9c-9db0-4a7f-8de9-3bdfd8388fa1)

**Comment by PAXANDDOS** [comment] 2023-10-06 11:17
Hi! I guess you have PAYDAY3 on the Microsoft Store, right?
Can you test that the issue is indeed with explorer.exe before modifying the fix? All this fix does is kill the explorer process after the game has started. Try running the game and killing explorer.exe manually from the task manager. If the game still crashes then it's a non-explorer-related issue. Also, none of these games use Xbox Networking, which makes this fix incompatible for them.
I'm closing the issue because it's not related to Forza Horizon, but you still can respond (without reopening)

**Closed as not planned by PAXANDDOS** 2023-10-06 11:17 UTC

**Comment by Sharshofe** [comment] 2023-10-06 18:39
well it did work manually! and i removed the script were it starts the xbox networking 
it just crashes idk why with the script
